apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-filestore-pv
spec:
  storageClassName: filestore-rwx
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.124.73.34
    path: /wordpress
  persistentVolumeReclaimPolicy: Retain
