apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-filestore-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-rwx
  resources:
    requests:
      storage: 10Gi  
  volumeName: wordpress-filestore-pv  
