apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: {{ .Values.mysql.dbHostKey | b64enc | quote }}
  DB_USER: {{ .Values.mysql.dbUserKey |  b64enc | quote }}
  DB_PASSWORD: {{ .Values.mysql.dbPasswordKey |  b64enc | quote }}
