controller:

  autoscaling:
    enabled: true
    minReplicas: 1  
    maxReplicas: 3  
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60

  replicaCount: 1  
  
  config:
    enableCORS: true
    # Example CORS settings, you can modify based on your needs
    allowOrigins: "*"
    allowMethods: "GET, POST, PUT, DELETE"
    allowHeaders: "Content-Type, Authorization, X-Requested-With"


  ingressClassResource:
    annotations:
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE"
      nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization, X-Requested-With"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"

  ingressController:
    customSnippet: |      
      more_set_headers 'X-Content-Type-Options: nosniff';
      more_set_headers 'X-XSS-Protection: 1; mode=block';
