name: WordPress CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  wordpress-theme-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl  google-cloud-sdk
           gcloud components install gke-gcloud-auth-plugin --quiet
      - name: Auth GKE
        run: |
          gcloud container clusters get-credentials interview-gke --region asia-southeast2 --project golden-resolver-455014-d8

      - name: Copy Theme to WordPress Pod
        run: |
          kubectl cp interview/helm/wordpress/themes/edu.zip default/$(kubectl get pod -l app=wordpress -o jsonpath="{.items[0].metadata.name}"):/var/www/html/wp-content/themes/

      - name: Install and Activate Theme
        run: |
          kubectl exec  $WP_POD -- bash -c "
            unzip -o /var/www/html/wp-content/themes/edu.zip -d /var/www/html/wp-content/themes/ &&
            wp theme activate edu --path=/var/www/html --url=https://darksoul.site
          "
