name: WordPress CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  wordpress-theme-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: golden-resolver-455014-d8
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: Auth GKE
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          gcloud components install kubectl
          gcloud container clusters get-credentials interview-gke --region asia-southeast2 --project golden-resolver-455014-d8

      - name: Copy Theme to WordPress Pod
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          kubectl cp interview/helm/wordpress/themes/edu.zip default/$(kubectl get pod -l app=wordpress -o jsonpath="{.items[0].metadata.name}"):/var/www/html/wp-content/themes/

      - name: Install and Activate Theme
        run: |
          kubectl exec  $(kubectl get pod -l app=wordpress -o jsonpath="{.items[0].metadata.name}") -- bash -c "
            unzip -o /var/www/html/wp-content/themes/edu.zip -d /var/www/html/wp-content/themes/ &&
            wp theme activate edu --path=/var/www/html --url=https://darksoul.site
          "
